Add Binary Data Type
pauwels-labs/redact-crypto pull request #4
Opened 2021-08-13 09:52 UTC by howhelan

2021-08-13 09:52 UTC, capt-haddock commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **howhelan**
You can assign the PR to them by writing `/assign @howhelan` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=pauwels-labs%2Fredact-crypto).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-crypto/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["howhelan"]} -->

2021-08-25 10:11 UTC, ajpauwels requested changes

2021-08-25 10:11 UTC, ajpauwels commented on src/data.rs
> +    pub binary: String,
I don't think this is an appropriate data type for the binary content. I believe a string HAS to be UTF-8 bytes, I'm surprised this works at all actually. I think a Vec<u8> would be more appropriate.

2021-08-25 10:11 UTC, ajpauwels commented on src/data.rs
> +                let s = String::from_utf8(binary_data_bytes.to_vec())
This goes along with the review comment re using a String as the data type (unless there's something I'm missing here). Should just be able to keep `binary_data_bytes.to_vec()` and remove the wrapping `from_utf8`

2021-08-30 08:59 UTC, merged